spring:
  application:
    name: logpulse

  datasource:
    url: jdbc:mysql://localhost:13306/logpulse
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      pool-name: LogPulseHikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: logpulse-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 병렬 처리 설정
      max-poll-records: 500
      fetch-max-wait: 500
      fetch-min-size: 1
      concurrency: 5
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
      retry.backoff.ms: 1000
      client.id: logpulse-client
    listener:
      concurrency: 5  # 컨슈머 리스너 스레드 수
      type: batch     # 배치 처리 설정

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  sql:
    init:
      mode: always
      platform: mysql

  elasticsearch:
    rest:
      uris: localhost:19200

logging:
  level:
    com.tenacy.logpulse: DEBUG
    org.springframework: INFO
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG

logpulse:
  batch:
    chunk-size: 100
    archive-days: 30
  collector:
    directory: ${user.home}/logpulse/logs
    file-pattern: "*.log"
  kafka:
    topics:
      raw-logs: raw-logs
  filter:
    excluded-sources: test-source
    min-level: INFO
  alert:
    error-threshold: 10
    error-time-window: 60000  # 1분
  cleanup:
    retention-days: 90
  elasticsearch:
    bulk-size: 1000
    index-prefix: logpulse-
    shards: 5
    replicas: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}