spring:
  application:
    name: logpulse

  datasource:
    url: jdbc:mysql://localhost:13306/logpulse?rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
      pool-name: LogPulseHikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      group-id: logpulse-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
      fetch-max-wait: 500
      fetch-min-size: 1
      concurrency: 5
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
      retry.backoff.ms: 1000
      client.id: logpulse-client
    listener:
      concurrency: 5
      type: batch
      ack-mode: MANUAL_IMMEDIATE

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  sql:
    init:
      mode: always
      platform: mysql

  elasticsearch:
    rest:
      uris: localhost:19200

logging:
  level:
    root: ERROR                   # 기본 로그 레벨을 ERROR로 설정
    com.tenacy.logpulse: WARN     # 애플리케이션 코드는 WARN만 출력
    org.springframework: ERROR    # Spring 프레임워크는 ERROR만 출력
    org.apache.kafka: ERROR       # Kafka 관련 로그는 ERROR만 출력
    org.springframework.kafka: ERROR # Spring Kafka 로그는 ERROR만 출력
    org.hibernate: ERROR          # Hibernate 로그는 ERROR만 출력
    org.hibernate.SQL: OFF        # SQL 쿼리 로그 완전 비활성화
    org.hibernate.type: OFF       # Hibernate 타입 로그 비활성화

logpulse:
  batch:
    chunk-size: 100
    archive-days: 30
  collector:
    directory: ${user.home}/logpulse/logs
    file-pattern: "*.log"
  kafka:
    topics:
      raw-logs: raw-logs
  filter:
    excluded-sources: test-source
    min-level: INFO
  alert:
    error-threshold: 10
    error-time-window: 60000  # 1분
  cleanup:
    retention-days: 90
  elasticsearch:
    bulk-size: 1000
    index-prefix: logpulse-
    shards: 5
    replicas: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
    enable:
      jvm: true
      process: true
      system: true
      logback: true
      tomcat: true