spring:
  datasource:
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
  kafka:
    consumer:
      group-id: logpulse-group
      max-poll-records: 500
      fetch-max-wait: 500
      fetch-min-size: 1
      concurrency: 5
    producer:
      client-id: logpulse-client
    properties:
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
      retry.backoff.ms: 1000
    listener:
      concurrency: 5
  elasticsearch:
    username:
    password:

logging:
  level:
    root: WARN
    com.tenacy.logpulse: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN

logpulse:
  collector:
    directory: /app/logs
    file-pattern: "*.log"
  kafka:
    topics:
      raw-logs: raw-logs-dev
  filter:
    min-level: DEBUG
  elasticsearch:
    index-prefix: logpulse-dev-
    shards: 5
    replicas: 1