spring:
  datasource:
    url: jdbc:mysql://mysql:3306/logpulse_test?rewriteBatchedStatements=true
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: LogPulseTestHikariPool
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: logpulse-test-group
      max-poll-records: 100
      concurrency: 3
    producer:
      client-id: logpulse-test-client
    listener:
      concurrency: 3
  elasticsearch:
    rest:
      uris: elasticsearch:9200

logging:
  level:
    root: WARN
    com.tenacy.logpulse: WARN
    org.springframework: ERROR
    org.hibernate: ERROR

logpulse:
  batch:
    chunk-size: 50
    archive-days: 7
  collector:
    directory: /app/test-logs
    file-pattern: "*.log"
  kafka:
    topics:
      raw-logs: raw-logs-test
  filter:
    min-level: DEBUG
  alert:
    email:
      enabled: true
  elasticsearch:
    bulk-size: 100
    index-prefix: logpulse-test-
    shards: 2
    replicas: 0

management:
  health:
    mail:
      enabled: false
    elasticsearch:
      enabled: false